### ISSUE TITLE
Markdown editor to create/edit post

### ISSUE THREAD

**Issue by baabeetaa** [baabeetaa/glogchain#5]
Browser markdown editor

**Comment by baabeetaa** [comment]
http://www.developersfeed.com/awesome-javascript-wysiwyg-markdown-editors/

**Comment by faddat** [comment]
* quill-js/quill
* medium-editor
* https://github.com/ajaxorg/ace
* benweet/stackedit
* facebook/draft-js

**Comment by baabeetaa** [comment]
use https://simplemde.com/
see https://github.com/baabeetaa/glogchain/commit/036f23beedf2d4a6f4c9acee446caf341e17064a

![screen shot 2017-01-15 at 4 03 41 am](https://cloud.githubusercontent.com/assets/11970690/21958090/af742792-dad7-11e6-98ae-40fe1ce61584.png)

![screen shot 2017-01-15 at 4 03 53 am](https://cloud.githubusercontent.com/assets/11970690/21958094/bc38a7dc-dad7-11e6-9f72-724cc01380df.png)
