### ISSUE TITLE
Minor Inqueries 

### ISSUE THREAD

**Issue by travis190** [baabeetaa/glogchain#9]
![image](https://cloud.githubusercontent.com/assets/24629215/22424932/6c88b62c-e72b-11e6-8f6d-3cd6b486a745.png)

'you' should mean [use] I believe..

![image](https://cloud.githubusercontent.com/assets/24629215/22424991/a49df4b4-e72b-11e6-8da2-12826188f200.png)

I am confused by the context of the text here... I understand it wants me to create some sort of secret code...but it just says 'bases (misspelled, should be "based") on your secret'

.... i think it would be better to say something like [ Generate a Keypair by creating a Public Key and Private Key... Create your Private Key by entering it below or clicking the following link http://passwordsgenerator.net/ ]

![image](https://cloud.githubusercontent.com/assets/24629215/22425200/8e4f43f6-e72c-11e6-80a0-d9e6e83e33e9.png)

This is also petty, but I think the words should have spaces between them like in the menu log you created below

![image](https://cloud.githubusercontent.com/assets/24629215/22425232/b35cef7c-e72c-11e6-9f86-dbc9e95bf837.png)

Also in regards to this picture, I think minimized options are nice... as in if you are logged in it is automatically detected and you only have the logout option or vice versa...

Anyways, everything is looking sweet, cheers for creating this!!!

**Comment by travis190** [comment]
So my screenshots didn't include the drop down menus for some reason... you will have to go to the glogchain and take a look at the menus yourself, apologies.

**Comment by travis190** [comment]
![image](https://cloud.githubusercontent.com/assets/24629215/22427103/5eabebce-e734-11e6-9095-082cd7bfa3f4.png)

When I click Submit nothing happens.

**Comment by baabeetaa** [comment]
got the bug, I'm fixing it now.
